name: tdevelopment

on:
  push:
  workflow_dispatch:
  workflow_call:

# concurrency:
#   group: ${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run linter
        run: make lint
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Run tests
        run: make unit
