name: production

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    uses: ./.github/workflows/development.yml

  package:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Run package
        run: make package
