name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  package:
    uses: fs/graphene-django-pretty/.github/workflows/tests.yml@main
    runs-on: ubuntu-latest
      - name: Run package
        run: make package
